In [4]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

from google.cloud import bigquery

client = bigquery.Client()

client = bigquery.Client()

dataset_ref = client.dataset("hacker_news", project="bigquery-public-data")

dataset = client.get_dataset(dataset_ref)

tables = list(client.list_tables(dataset))

Using Kaggle's public dataset BigQuery integration.
Using Kaggle's public dataset BigQuery integration.

In [5]:
for table in tables:  
    print(table.table_id)

full

In [8]:
tables = list(client.list_tables(dataset))

In [10]:
table_ref = dataset_ref.table("full")

In [11]:
table = client.get_table(table_ref)

In [12]:
table.schema

[SchemaField('title', 'STRING', 'NULLABLE', None, 'Story title', (), None, None),
 SchemaField('url', 'STRING', 'NULLABLE', None, 'Story url', (), None, None),
 SchemaField('text', 'STRING', 'NULLABLE', None, 'Story or comment text', (), None, None),
 SchemaField('dead', 'BOOLEAN', 'NULLABLE', None, 'Is dead?', (), None, None),
 SchemaField('by', 'STRING', 'NULLABLE', None, "The username of the item's author.", (), None, None),
 SchemaField('score', 'INTEGER', 'NULLABLE', None, 'Story score', (), None, None),
 SchemaField('time', 'INTEGER', 'NULLABLE', None, 'Unix time', (), None, None),
 SchemaField('timestamp', 'TIMESTAMP', 'NULLABLE', None, 'Timestamp for the unix time', (), None, None),
 SchemaField('type', 'STRING', 'NULLABLE', None, 'type of details (comment comment_ranking poll story job pollopt)', (), None, None),
 SchemaField('id', 'INTEGER', 'NULLABLE', None, "The item's unique id.", (), None, None),
 SchemaField('parent', 'INTEGER', 'NULLABLE', None, 'Parent comment ID', (), None, None),
 SchemaField('descendants', 'INTEGER', 'NULLABLE', None, 'Number of story or poll descendants', (), None, None),
 SchemaField('ranking', 'INTEGER', 'NULLABLE', None, 'Comment ranking', (), None, None),
 SchemaField('deleted', 'BOOLEAN', 'NULLABLE', None, 'Is deleted?', (), None, None)]

In [13]:
client.list_rows(table, max_results=5).to_dataframe()

,title,url,text,dead,by,score,time,timestamp,type,id,parent,descendants,ranking,deleted
0,A new business model emerges that could save g...,http://startupcrunch.org/do_no_evil_or_do_no_good,None,<NA>,agentbleu,1,1174230594,2007-03-18 15:09:54+00:00,story,4852,<NA>,1,<NA>,<NA>
1,AI forgoes toxic positivity for neurodivergents,https://medium.com/@mantaman555/the-daily-exha...,None,<NA>,FDX2018,5,1781374963,2026-06-13 18:22:43+00:00,story,48520000,<NA>,0,<NA>,<NA>
2,Google Gemini-SQL2 tops text-to-SQL benchmarks,https://the-decoder.com/google-researchs-gemin...,None,<NA>,geox,3,1781375005,2026-06-13 18:23:25+00:00,story,48520007,<NA>,0,<NA>,<NA>
3,Invoice To Me,http://invoiceto.me,None,<NA>,dotmanish,1,1354253425,2012-11-30 05:30:25+00:00,story,4852001,<NA>,2,<NA>,<NA>
4,Rows Are Made for Sorting and That's Just What...,https://duckdb.org/pdf/ICDE2023-kuiper-muehlei...,None,<NA>,tosh,4,1781375163,2026-06-13 18:26:03+00:00,story,48520025,<NA>,0,<NA>,<NA>

In [14]:
client.list_rows(table, selected_fields=table.schema[:1], max_results=5).to_dataframe()

                                               title
0  A new business model emerges that could save g...
1    AI forgoes toxic positivity for neurodivergents
2     Google Gemini-SQL2 tops text-to-SQL benchmarks
3                                      Invoice To Me
4  Rows Are Made for Sorting and That's Just What...